### ISSUE TITLE
Bug - Build failed

### ISSUE THREAD

**Issue by gregLibert** [massalabs/docu-dev#30]
```shell
$npm run build

> docu-dev@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 11.80s


✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docu-dev/docs/build/smart-contract/webassembly-module:
   -> linking to ./quick-start (resolved as: /docu-dev/docs/build/smart-contract/quick-start)

    at throwError (/home/greg/code/docu-dev/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at handleBrokenLinks (/home/greg/code/docu-dev/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
    at async buildLocale (/home/greg/code/docu-dev/node_modules/@docusaurus/core/lib/commands/build.js:186:5)
    at async tryToBuildLocale (/home/greg/code/docu-dev/node_modules/@docusaurus/core/lib/commands/build.js:41:20)
    at async mapAsyncSequential (/home/greg/code/docu-dev/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/home/greg/code/docu-dev/node_modules/@docusaurus/core/lib/commands/build.js:76:21)
[INFO] Docusaurus version: 2.4.0
Node version: v19.7.0
```

**Comment by qdrn** [comment]
It works on the main branch, not on the PR you reviewed this morning. Closing.
